---

 - name: Provision EC2 Box
   local_action:
     module: ec2
     profile: "{{Account}}"
     key_name: "{{KeyPair}}"
     region: "{{Region}}"
     instance_type: "{{Instance_Type}}"
     vpc_subnet_id: "{{Subnet_ID}}"
     group_id: "{{Security_Groups}}"
     aws_zone: "{{Availability_Zone}}"
     image: "{{AMI_ID}}"
     user_data: "${file('/tmp/ec2_user_data.sh')}"
     monitoring: "{{Enable_Monitoring}}"
     volumes:
       - device_name: /dev/sda1
         device_type: "{{Disk_Type}}"
         volume_size: 25
         delete_on_termination: true
     wait: yes
     instance_tags:
       Name: "{{Name_Tag}}"
       Email: "{{Email_Tag}}"
       Team: "{{Team_Tag}}"
       Project: "{{Project_Tag}}"
       Environment: "{{Environment_Tag}}"
     wait: true
     count: 1
     assign_public_ip: yes
   register: ec2

 - debug: msg={{ec2}}
 - pause: seconds=30

 - name: Create and attach a volumes
   ec2_vol:
       profile: "{{Account}}"
       instance: "{{ ec2.instance_ids[0] }}"
       name: "{{ ec2.instance_ids[0] }}"
       volume_size: "{{Disk_Size}}"  # in GB
       volume_type: "{{Disk_Type}}"
       device_name: /dev/sdf
       region: "{{Region}}"
       delete_on_termination: true
#       with_items: ec2.instances
   when: "{{ Disk_Size }} != 0"
   register: ec2_vol
 - debug: msg={{ec2_vol}}
